project:
  name: "Europe Housing Trends"
  author: "Yordan Bahchevanov"
  version: "1.0"
  description: >
    Analysis of housing price dynamics across Europe with a focus on Bulgaria,
    exploring correlations with net earnings, GDP per capita, unemployment,
    and inflation (Eurostat data, 2015–2024).

paths:
  raw_data: "data/raw/"
  processed_data: "data/processed/"
  figures: "reports/figures/"
  notebooks: "notebooks/"
  scripts: "scripts/"

analysis:
  start_year: 2015
  end_year: 2024
  focus_country: "Bulgaria"

reporting:
  docs: "docs/"
  results: "docs/03_conclusion.md"
  readme: "README.md"

environment:
  file: "environment.yml"
  python: "3.12"
